version: '3.9'

services:
  web:
    build: .
    depends_on:
      mydb:
        condition: service_healthy
      waha:  # Adicionado a dependência da API WAHA
        condition: service_started
    ports:
      - "8069:8069"
      - "5678:5678"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ./odoo:/mnt/extra-addons
      - ./entrypoint.sh:/entrypoint.sh
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: bash /entrypoint.sh

  mydb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  waha:
    image: devlikeapro/waha
    container_name: waha_api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./waha_data:/root/.waha